spring:
  profiles:
    active: db
  messages:
    encoding: UTF-8

logging:
  level:
    root:  DEBUG
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    com.fei.shop.mapper:  DEBUG
#    mapper:  DEBUG

#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
