spring:
  profiles:
    active: db

server:
  port: ${random.int[8080,9000]}

dubbo:
  protocol:
    port: ${random.int[20880,20980]}
    name: dubbo
  application:
    name: module_system
    qosEnable: false
  scan:
    basePackages: com.fei.shop
  registry:
    id: module_system_registry
    address: nacos://47.115.124.84:8848

logging:
  level:
#    root:  DEBUG
#    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    com.fei.shop.mapper:  DEBUG
#    mapper:  DEBUG





